export const SET_STORE = "SET_STORE";
export const UPDATE_FILTERED = "UPDATE_FILTERED";
export const SET_SORT_COLUMN = "SET_SORT_COLUMN";
export const SET_SORT_DIRECTION = "SET_SORT_DIRECTION";
export const UPDATE_FORM_STATE = "UPDATE_FORM_STATE";
